# Configuración de la Base de Datos (Supabase)
spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.ukgnvwsbngzsydhrwzeq
spring.datasource.password=0xPNrz7QZSxavwki
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.type.json_format_mapper=jackson

# Puerto de la aplicación
server.port=8080